#!/usr/bin/env python3
import gzip, base64, os

logo_path = "/usr/share/pixmaps/system-logo-white.png"
if not os.path.exists(logo_path):
    print("Logo not found, skipping")
    exit(0)

with open(logo_path, 'rb') as f:
    data = base64.b64encode(f.read()).decode()

svg = f'''<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="256" height="256">
  <image xlink:href="data:image/png;base64,{data}" width="256" height="256"/>
</svg>'''

paths = [
    "/usr/share/plasma/look-and-feel/com.valve.vapor.desktop/contents/splash/images/bazzite_logo.svgz",
    "/usr/share/plasma/look-and-feel/com.valve.vgui.desktop/contents/splash/images/bazzite_logo.svgz"
]

for path in paths:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with gzip.open(path, 'wb') as f:
        f.write(svg.encode())
    print(f"Replaced: {path}")
